apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mini-demo1
data:
  # These key-value pairs will be available as environment variables in the pods
  APP_NAME: "Kubernetes Mini Demo"
  APP_VERSION: "1.0.0"
